### ISSUE TITLE
[Session]: Session3: Lifecycle の参考資料にある iOS 側のリンク先の変更

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-training-template#35]
### 現状

> How do I listen to iOS lifecycle events?　

の部分のリンクが↓のようになっており、リンク切れが発生している
https://docs.flutter.dev/get-started/flutter-for/ios-devs#how-do-i-listen-to-ios-lifecycle-events

### 動機

以前のリンク先の内容が記載されている URL に修正する

### 提案

リンク先を↓に変更する
https://docs.flutter.dev/get-started/flutter-for/uikit-devs#listening-to-lifecycle-events

**Comment by Yamasaki-pan961** [comment]
✋やります
