### ISSUE TITLE
[Session]: yumemi_weatherのアプデ提案

### ISSUE THREAD

**Issue by K9i-0** [yumemi-inc/flutter-training-template#40]
### 現状

- 1️⃣ Session 5で使うyumemi_weatherのString fetchThrowsWeather(String area)がareaを引数に持つ
https://github.com/yumemi-inc/flutter-training-template/blob/428cd362df558df47c6f809a2c30895dae3f7565/packages/yumemi_weather/lib/src/yumemi_weather_base.dart#L121
- 2️⃣ 要求SDKバージョンが古い
https://github.com/yumemi-inc/flutter-training-template/blob/428cd362df558df47c6f809a2c30895dae3f7565/packages/yumemi_weather/pubspec.yaml#L7

### 動機

- 1️⃣ 研修課題を行う上でareaは必要ないと思われるが、存在しない意図を深読みして研修に集中できないかもしれないので不要なら消したい
- 2️⃣ 1️⃣のついでに更新しときたい

### 提案

- 1️⃣ areaを引数から消す
- 2️⃣ 公式に習ってsdk: '>=2.18.0 <4.0.0'にするのが良さそう
https://github.com/firebase/flutterfire/pull/10946

**Comment by blendthink** [comment]
@K9i-0 
ご提案ありがとうございます！！

### 1️⃣ について

fetchThrowsWeather の area を無くすのであれば、 fetchWeather の jsonString の area も無くした方がよさそうですね。。

ただ、この研修課題の意図として yumemi_weather を公開されていない Web API のように使ってもらいたいという想いがあります。
本来であれば、どこかに Web API をデプロイして、アプリでは HttpClient を定義してそれを呼び出す、というようにしたほうがいいのかもしれませんが、メリット・デメリットを考えてそこまでは対応していません。

また、引数を String → JSON というように段階的に複雑にして渡すように課題を構成しており、どこでどのように引数を用意して受け渡すのが良いのかを新卒の方々に自然と感じてもらうのも１つの狙いだったりします。

しかし、ご指摘のとおり、現状意味のないコードになっており、多少無駄な時間を費やしてしまう可能性があるため、これを意味のあるコードに変える方がメリットが大きそうな気がしているのですがいかがでしょうか？

### 2️⃣ について

これは念の為、最新の Dart でも動作確認した上で対応しておきたいですね、、！
LGTM です！

**Comment by K9i-0** [comment]
>ただ、この研修課題の意図として yumemi_weather を公開されていない Web API のように使ってもらいたいという想いがあります。
本来であれば、どこかに Web API をデプロイして、アプリでは HttpClient を定義してそれを呼び出す、というようにしたほうがいいのかもしれませんが、メリット・デメリットを考えてそこまでは対応していません。
>
>また、引数を String → JSON というように段階的に複雑にして渡すように課題を構成しており、どこでどのように引数を用意して受け渡すのが良いのかを新卒の方々に自然と感じてもらうのも１つの狙いだったりします。

なるほどそういうことだったんですね👍
同じようなAPIのI/Oに統一感無いのが気になっちゃたんですけど、研修課題の狙いとしては良さそうに感じました。

>しかし、ご指摘のとおり、現状意味のないコードになっており、多少無駄な時間を費やしてしまう可能性があるため、これを意味のあるコードに変える方がメリットが大きそうな気がしているのですがいかがでしょうか？

段階に複雑にする狙いがわかったので、今のままでも良い気がしています。
同じことが気になった人むけにリポジトリのどこかに、今のようになってる意図が説明されていると良いかもです。（このIssueに気づけば分かりそうですが）
