### ISSUE TITLE
[Template]:InitWorkFlow内の一時ディレクトリ名HardCodeはやめた方がいい気がします

### ISSUE THREAD

**Issue by ika020202** [yumemi-inc/flutter-training-template#41]
### 現状

ゆめみ社員ではなく、全く関係のない外部の人間ですが気になった箇所があったので提起です🙋‍♂️
ref: https://twitter.com/urasan_edu/status/1658702322384642048

template-cleanup.yamlファイル内で一時ディレクトリを作成しているが、ディレクトリ名を直接指定している。

### 動機

保守性から見てHardCodeはやめた方がいい気がします。
良いWorkFlowなので他のプロジェクトに再利用できうると思います。
そうして移行した時に移行先にtempディレクトリは割と存在しがちなので...

#### 案1
```bash
tmp_dir="$(mktemp -d)"
```
を使用して一時ディレクトリを作り、その後はBash内変数を使用する
(重複名を避ける意図＆改修箇所を減らす意図)

#### 案2
GithubActionsのenvパラメータにtempを指定して、参照はtemp定数を取るようにする。
(改修箇所を減らす意図)

ゆめみさんのコーディング規約や社内ルールについて詳しくないので、とりあえず2案です。
Issue提起自体が微妙なら遠慮なくRejectしちゃってください〜。

**Comment by blendthink** [comment]
@ika020202 
ご提案ありがとうございます！

これについては「これは良くないよなぁ、、」と思いながら実装していた部分でしたのでとても助かります 😍 

来週、チームでもどのように対応するか検討して進めていきます！

**Comment by blendthink** [comment]
@ika020202 CC: @morikann 
遅くなってしまいましたが、こちら進めさせていただきます 🙏 

ただ、社内で検討した結果、保守性の向上が目的なので Dart で書きたい！ということになり、Cleanup 部分の処理をまるっと Dart CLI App を開発して差し替えることとなりました。
ですので、もうしばらくお待ちいただければと思います 🙇
