### ISSUE TITLE
[Session]: Session0 - プロジェクト内で設定される Flutter SDK バージョンが `yumemi_lints` と互換性がない場合に Dart Analyzer が失敗する

### ISSUE THREAD

**Issue by Kotaro666-dev** [yumemi-inc/flutter-training-template#60]
### 現状

`.github/workflows/template-cleanup.yaml` のコマンド実行で取得された最新の Flutter stable バージョンがプロジェクト内で使用される Flutter SDK バージョンという認識です。

```yaml
# Install & Setup Flutter
flutterLatestVersion=$(fvm releases | grep -o -E "v?[0-9]+\.[0-9]+\.[0-9]+\s+stable" | sed -e "s/[ ]*stable//g")
fvm install "$flutterLatestVersion"
fvm use "$flutterLatestVersion" --force
```

https://github.com/yumemi-inc/flutter-training-template/blob/main/.github/workflows/template-cleanup.yaml#L45-L47

ここで取得した最新の Flutter stable バージョンが設定される `yumemi_lints` で参照するものと互換性がない場合に、Dart Analyzer が失敗します。失敗するため、`yumemi_lints` で用意されているバージョンにダウングレードする必要がありました。

```yaml
# Override the analysis_options.yaml
cat <<EOF > analysis_options.yaml
# https://pub.dev/packages/yumemi_lints
include: package:yumemi_lints/flutter/$flutterLatestVersion/recommended.yaml
EOF
```

https://github.com/yumemi-inc/flutter-training-template/blob/main/.github/workflows/template-cleanup.yaml#L60-L68

### 動機

私が[Flutter 研修課題の Session 0](https://github.com/Kotaro666-dev/flutter-training-202312/issues/1)に対応した際に、現状で説明した状態が発生しました。

`yumemi_lints`パッケージが最新の Flutter バージョンに互換性があるように対応するのは日本時間毎週金曜日となっています。

```
on:
  workflow_dispatch:
  schedule:
    # Schedule at 9 AM JST (0 AM UTC) every Friday
    - cron: '0 0 * * 5'
```

https://github.com/yumemi-inc/flutter-yumemi-lints/blob/main/.github/workflows/update-lint-rules.yaml#L3-L7

研修課題プロジェクトをスタートするタイミングによっては、私と同じように初回 Session 0 の PR 作成時に Dart Analyzer の失敗でコケてしまう人がいるように思いました。

同様のエラーが発生する人向けに何か参考資料としてエラー時の対応方法をまとめられないかと思います。

### 提案

- 研修課題 プロジェクトの Wiki に、今回報告するエラーの対応方法を記載したページを作成する
- 作成した Wiki を Session 0 の参考資料の項目に追加する

**Comment by blendthink** [comment]
Wiki の ↓ にページを作成。
https://github.com/yumemi-inc/flutter-training-template/wiki/Error-occurs-when-yumemi_lints-does-not-support-the-latest-version-of-Flutter-SDK
