### ISSUE TITLE
[Session]: Session 9 - 参考資料を更新する

### ISSUE THREAD

**Issue by Kotaro666-dev** [yumemi-inc/flutter-training-template#61]
### 現状

- Mockito: https://docs.flutter.dev/cookbook/testing/unit/mocking
- Riverpod: https://docs-v2.riverpod.dev/docs/cookbooks/testing

issue 内に言及されている Mocikto のリンクは、 Flutter 公式ドキュメントであり、Mockito パッケージの公式のものではないです。
参考資料に挙げられている Riverpod のリンクは、古いガイドのものとなっています。

### 動機

Mockito パッケージの[公式ドキュメント](https://pub.dev/packages/mockito)にはよりたくさんの情報が書いてあると同時に、モック作成時に使用する推奨アノテーションが Flutter 公式ドキュメントのものと異なります。

- Mockito 公式ドキュメント: `@GenerateNiceMocks`
- Flutter 公式ドキュメント: `@GenerateMocks`

Riverpod に関しては、[最新のテストに関するドキュメント](https://docs-v2.riverpod.dev/docs/essentials/testing)をリンクしてあげたほうが良さそうだと思いました。

### 提案

参考資料を以下の状態に変更する

- [Testing your providers](https://docs-v2.riverpod.dev/docs/essentials/testing)
- [mockito | REAMDME](https://pub.dev/packages/mockito)

**Comment by blendthink** [comment]
↓ は最新に更新されていたので、こちらは修正不要そうです。タイトルだけ修正しておきます 🙆‍♂️ 

https://riverpod.dev/docs/essentials/testing
